student:
  file:
    path: C:\Users\gabrielamaciac\Documents\GitHub\student
    successful: C:\Users\gabrielamaciac\Documents\GitHub\student\successful
    archived: C:\Users\gabrielamaciac\Documents\GitHub\student\archived
